### ISSUE TITLE
Cannot find module './FormattedInspectObject' in node module s3p

### ISSUE THREAD

**Issue by siebrand** [art-suite/art-suite-foundations#7]
I'm using s3p, and this appears to have been broken since the latest version of this module. I wasn't really sure who's to blame, so reported it in both projects.

Also see: https://github.com/generalui/s3p/issues/22

Getting this with a new install since 2020-12-31:

```
npx s3p sync --bucket $SOURCEBUCKET --to-bucket $TARGETBUCKET --overwrite --max-queue-size 20000 --list-concurrency 50
Cannot find module './FormattedInspectObject'
Require stack:
- /root/node_modules/art-standard-lib/source/Art.StandardLib/Inspect/FormattedInspect.js
- /root/node_modules/art-standard-lib/source/Art.StandardLib/Inspect/Inspect.js
- /root/node_modules/art-standard-lib/source/Art.StandardLib/Inspect/index.js
- /root/node_modules/art-standard-lib/source/Art.StandardLib/ErrorWithInfo.js
- /root/node_modules/art-standard-lib/source/Art.StandardLib/Promise.js
- /root/node_modules/art-standard-lib/source/Art.StandardLib/StandardLib.js
- /root/node_modules/art-standard-lib/source/Art.StandardLib/index.js
- /root/node_modules/art-standard-lib/index.js
- /root/node_modules/s3p/source/S3Parallel/StandardImport.js
- /root/node_modules/s3p/source/S3Parallel/Lib/S3Keys.js
- /root/node_modules/s3p/source/S3Parallel/Lib/Lib.js
- /root/node_modules/s3p/source/S3Parallel/Lib/index.js
- /root/node_modules/s3p/source/S3Parallel/S3Parallel.js
- /root/node_modules/s3p/source/S3Parallel/index.js
- /root/node_modules/s3p/source/index.js
- /root/node_modules/s3p/bin/s3p
```

As far as I can tell with my limited knowledge, it may be solely an issue in this modules. Here is the grep result in all installed modules:

```
grep -r FormattedInspectObject *
art-standard-lib/source-source/Art.StandardLib/Inspect/FormattedInspect.caf:  &FormattedInspectObject
art-standard-lib/source/Art.StandardLib/Inspect/FormattedInspect.js:      require("./FormattedInspectObject"),
art-standard-lib/source/Art.StandardLib/Inspect/index.js:  FormattedInspectObject:  require('./formattedInspectObject'),
```

**Comment by siebrand** [comment]
Wasn't really familiar with using an older module version. This works with `npm install art-standard-lib@1.70.6`.

**Comment by shanebdavis** [comment]
I'll get right on it. Thanks!

**Comment by shanebdavis** [comment]
Aha! Subtle. It was a case-sensitivity bug. I develop on Mac, and as you probably know, Mac ignores file-name case. `FormattedInspectObject.js` existed, but as `formattedInspectObject.js`. Even more annoying, git doesn't let you change the case of an existing object within one commit, so you have to delete them, commit, then add them back in with the correct case, commit.

Anyway, I added CI to s3p, which runs on linux and IS case sensitive, so we'll be able to catch this sort of bug automatically in the future. Thanks so much for reporting it!

**Comment by siebrand** [comment]
Thanks for the quick fix. 

I think you should be able to rename a file using "`git mv old new`" in shell. The will keep your git history in tact.
